In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [2]:
# want to move WP_Increase column to the end
data = pd.read_csv('coinbase_data_clean.csv',index_col='Timestamp')
output = data['WP_Increase']
data.drop(labels=['WP_Increase','Unnamed: 0'],axis=1,inplace=True)
data.insert(len(data.columns),'WP_Increase',output)

In [3]:
data.index = pd.to_datetime(data.index)
data

Open     High      Low    Close    Volume_BTC    Volume_USD  \
Timestamp                                                                    
2015-04-13   237.57   238.00   220.77   225.73  11641.757952  2.682148e+06   
2015-04-14   225.42   226.90   216.92   221.05  12054.596084  2.666821e+06   
2015-04-15   221.05   224.52   218.09   224.35   8708.367431  1.933906e+06   
2015-04-16   224.35   230.75   223.66   229.45   8248.389761  1.881515e+06   
2015-04-17   229.45   230.08   220.46   223.62   7338.967548  1.652133e+06   
...             ...      ...      ...      ...           ...           ...   
2019-01-01  3691.87  3841.17  3651.02  3826.10  10347.590883  3.840389e+07   
2019-01-02  3826.10  3916.57  3770.07  3890.79   9611.282751  3.688630e+07   
2019-01-03  3890.80  3893.80  3758.07  3787.57   8840.254922  3.382343e+07   
2019-01-04  3787.57  3849.00  3730.00  3820.82   8950.110359  3.387391e+07   
2019-01-05  3820.82  3874.12  3775.00  3798.62   6057.934757  2.322994e+07   

            Weighted_Price         ma10         ma50        ma100  \
Timestamp                                                           
2015-04-13      233.545702   246.729993   260.814036   258.526647   
2015-04-14      221.570503   243.495826   260.497650   257.392352   
2015-04-15      222.241195   240.101389   260.158047   255.836215   
2015-04-16      227.817999   236.953587   259.940846   254.336212   
2015-04-17      224.980171   233.883770   259.698071   252.815013   
...                    ...          ...          ...          ...   
2019-01-01     3700.539528  3819.206854  4052.495977  5238.905840   
2019-01-02     3823.152158  3803.664620  4003.122784  5210.750806   
2019-01-03     3829.900978  3774.049765  3959.304746  5184.900157   
2019-01-04     3785.337456  3775.216241  3925.107855  5158.127796   
2019-01-05     3834.565401  3781.169329  3891.174072  5131.280787   

            Ma10_WP_Increase  Ma50_WP_Increase  Ma100_WP_Increase        rsi  \
Timestamp                                                                      
2015-04-13                 0                 0                  0  32.866182   
2015-04-14                 0                 0                  0  26.713888   
2015-04-15                 0                 0                  0  27.532087   
2015-04-16                 0                 0                  0  34.118478   
2015-04-17                 0                 0                  0  32.499774   
...                      ...               ...                ...        ...   
2019-01-01                 0                 0                  0  45.244528   
2019-01-02                 1                 0                  0  49.696821   
2019-01-03                 1                 0                  0  49.938112   
2019-01-04                 1                 0                  0  48.290909   
2019-01-05                 1                 0                  0  50.243372   

            RSI_GreaterThan_50  WP_Increase  
Timestamp                                    
2015-04-13                   0            0  
2015-04-14                   0            1  
2015-04-15                   0            1  
2015-04-16                   0            0  
2015-04-17                   0            0  
...                        ...          ...  
2019-01-01                   0            1  
2019-01-02                   0            1  
2019-01-03                   0            0  
2019-01-04                   0            1  
2019-01-05                   1            1  

[1364 rows x 16 columns]

In [4]:
data.shape

(1364, 16)

In [5]:
test_data_size = int(.3*len(data))
train_data = data[:-test_data_size] # start from index 0 to int(.3*len(data)) before final row
test_data = data[-test_data_size:] # start from index int(.3*len(data)) onward

In [6]:
train_data.shape

(955, 16)

In [7]:
train_data

Open     High      Low    Close    Volume_BTC    Volume_USD  \
Timestamp                                                                    
2015-04-13   237.57   238.00   220.77   225.73  11641.757952  2.682148e+06   
2015-04-14   225.42   226.90   216.92   221.05  12054.596084  2.666821e+06   
2015-04-15   221.05   224.52   218.09   224.35   8708.367431  1.933906e+06   
2015-04-16   224.35   230.75   223.66   229.45   8248.389761  1.881515e+06   
2015-04-17   229.45   230.08   220.46   223.62   7338.967548  1.652133e+06   
...             ...      ...      ...      ...           ...           ...   
2017-11-18  7714.70  7847.98  7502.00  7777.01  14531.700663  1.116767e+08   
2017-11-19  7777.01  8098.62  7700.00  8031.82  14085.483398  1.115954e+08   
2017-11-20  8031.83  8293.25  7969.00  8256.01  15479.896162  1.264800e+08   
2017-11-21  8256.01  8375.00  7802.99  8109.00  29504.806698  2.396179e+08   
2017-11-22  8109.00  8298.98  8103.13  8250.00  13107.940089  1.074391e+08   

            Weighted_Price         ma10         ma50        ma100  \
Timestamp                                                           
2015-04-13      233.545702   246.729993   260.814036   258.526647   
2015-04-14      221.570503   243.495826   260.497650   257.392352   
2015-04-15      222.241195   240.101389   260.158047   255.836215   
2015-04-16      227.817999   236.953587   259.940846   254.336212   
2015-04-17      224.980171   233.883770   259.698071   252.815013   
...                    ...          ...          ...          ...   
2017-11-18     7714.778844  6987.605861  5909.709699  5025.846459   
2017-11-19     7839.763237  7046.875070  5981.112282  5069.077280   
2017-11-20     8126.735070  7162.908703  6057.401394  5112.434711   
2017-11-21     8185.441891  7325.662864  6132.887809  5153.875284   
2017-11-22     8210.158268  7536.938053  6210.741840  5194.201667   

            Ma10_WP_Increase  Ma50_WP_Increase  Ma100_WP_Increase        rsi  \
Timestamp                                                                      
2015-04-13                 0                 0                  0  32.866182   
2015-04-14                 0                 0                  0  26.713888   
2015-04-15                 0                 0                  0  27.532087   
2015-04-16                 0                 0                  0  34.118478   
2015-04-17                 0                 0                  0  32.499774   
...                      ...               ...                ...        ...   
2017-11-18                 1                 1                  1  66.049068   
2017-11-19                 1                 1                  1  67.304111   
2017-11-20                 1                 1                  1  70.042417   
2017-11-21                 1                 1                  1  70.585154   
2017-11-22                 1                 1                  1  70.824804   

            RSI_GreaterThan_50  WP_Increase  
Timestamp                                    
2015-04-13                   0            0  
2015-04-14                   0            1  
2015-04-15                   0            1  
2015-04-16                   0            0  
2015-04-17                   0            0  
...                        ...          ...  
2017-11-18                   1            1  
2017-11-19                   1            1  
2017-11-20                   1            1  
2017-11-21                   1            1  
2017-11-22                   1            0  

[955 rows x 16 columns]

In [8]:
# normalize columns
scaler = MinMaxScaler()
scaler = scaler.fit(train_data)
train_data = scaler.transform(train_data)
test_data = scaler.transform(test_data)

In [9]:
test_data[:,-1]

array([0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1.,
       0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1.,
       0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1.,
       1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1.,
       0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1.,
       1., 0., 1., 0., 1.

In [10]:
np.expand_dims(train_data,axis=1)

array([[[3.28284555e-03, 1.71268170e-03, 2.72378247e-02, ...,
         2.24121409e-01, 0.00000000e+00, 0.00000000e+00]],

       [[1.77256257e-03, 3.50878915e-04, 2.67626961e-02, ...,
         1.47185735e-01, 0.00000000e+00, 1.00000000e+00]],

       [[1.22935791e-03, 5.88887689e-05, 2.69070858e-02, ...,
         1.57417479e-01, 0.00000000e+00, 1.00000000e+00]],

       ...,

       [[9.72133725e-01, 9.89970507e-01, 9.83447015e-01, ...,
         6.89017716e-01, 1.00000000e+00, 1.00000000e+00]],

       [[1.00000000e+00, 1.00000000e+00, 9.62959718e-01, ...,
         6.95804751e-01, 1.00000000e+00, 1.00000000e+00]],

       [[9.81726198e-01, 9.90673491e-01, 1.00000000e+00, ...,
         6.98801622e-01, 1.00000000e+00, 0.00000000e+00]]])

In [11]:
test_data.shape

(409, 16)

### Sliding Window
- testing increments of data to find best results

In [12]:
def sliding_windows(data,seq_length):
    xs = []
    ys = []
    
    for i in range(len(data)-seq_length-1): # iterates through seq and starts at beginning of next sequence
        x = data[i:(i+seq_length)] # get all columns except last
        y = data[i+seq_length] # exactly the next index after x
        xs.append(x)
        ys.append(y)
    
    return np.array(xs),np.array(ys)

In [13]:
seq_length = 5 # train model based on sequences of 5 days

X_train, y_train = sliding_windows(train_data,seq_length)
X_test, y_test = sliding_windows(test_data,seq_length)

In [14]:
X_train.shape

(949, 5, 16)

In [56]:
y_train.flatten().shape

torch.Size([15184])

In [16]:
X_train[:2] # taking first and second sequence - expect 5 matrices

array([[[3.28284555e-03, 1.71268170e-03, 2.72378247e-02, 1.81109654e-03,
         6.64686733e-02, 7.53316718e-03, 2.19683644e-03, 2.79194145e-03,
         4.56274981e-03, 4.08329213e-03, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 2.24121409e-01, 0.00000000e+00, 0.00000000e+00],
        [1.77256257e-03, 3.50878915e-04, 2.67626961e-02, 1.22935791e-03,
         6.89728624e-02, 7.48174794e-03, 6.98845775e-04, 2.34954842e-03,
         4.50981768e-03, 3.85441496e-03, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 1.47185735e-01, 0.00000000e+00, 1.00000000e+00],
        [1.22935791e-03, 5.88887689e-05, 2.69070858e-02, 1.63955823e-03,
         4.86753452e-02, 5.02303611e-03, 7.82743426e-04, 1.88523236e-03,
         4.45300143e-03, 3.54041881e-03, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 1.57417479e-01, 0.00000000e+00, 1.00000000e+00],
        [1.63955823e-03, 8.23215916e-04, 2.75944796e-02, 2.27350417e-03,
         4.58852176e-02, 4.84727998e-03, 1.48035

In [44]:
y_train

tensor([[1.5401e-03, 0.0000e+00, 2.7412e-02,  ..., 2.0850e-01, 0.0000e+00,
         1.0000e+00],
        [1.6010e-03, 3.2880e-04, 2.7567e-02,  ..., 2.2816e-01, 0.0000e+00,
         1.0000e+00],
        [1.5998e-03, 4.1836e-04, 2.7569e-02,  ..., 2.3440e-01, 0.0000e+00,
         1.0000e+00],
        ...,
        [9.4046e-01, 9.6609e-01, 9.5025e-01,  ..., 6.5477e-01, 1.0000e+00,
         1.0000e+00],
        [9.7213e-01, 9.8997e-01, 9.8345e-01,  ..., 6.8902e-01, 1.0000e+00,
         1.0000e+00],
        [1.0000e+00, 1.0000e+00, 9.6296e-01,  ..., 6.9580e-01, 1.0000e+00,
         1.0000e+00]])

In [45]:
y_test

tensor([[1.1880, 1.1981, 1.1978,  ..., 0.8541, 1.0000, 1.0000],
        [1.2104, 1.3816, 1.0608,  ..., 0.8862, 1.0000, 0.0000],
        [1.2069, 1.3036, 1.1274,  ..., 0.7596, 1.0000, 1.0000],
        ...,
        [0.4493, 0.4530, 0.4653,  ..., 0.4346, 0.0000, 1.0000],
        [0.4574, 0.4502, 0.4638,  ..., 0.4376, 0.0000, 0.0000],
        [0.4446, 0.4447, 0.4603,  ..., 0.4170, 0.0000, 1.0000]])

### Create Model

In [19]:
# Pytorch Libraries
import torch
import torch.nn as nn # helps create models
import torch.nn.functional as F

In [21]:
X_train = torch.from_numpy(X_train).float()
y_train = torch.from_numpy(y_train).float()
X_test = torch.from_numpy(X_test).float()
y_test = torch.from_numpy(y_test).float()

In [46]:
y_train

tensor([[1.5401e-03, 0.0000e+00, 2.7412e-02,  ..., 2.0850e-01, 0.0000e+00,
         1.0000e+00],
        [1.6010e-03, 3.2880e-04, 2.7567e-02,  ..., 2.2816e-01, 0.0000e+00,
         1.0000e+00],
        [1.5998e-03, 4.1836e-04, 2.7569e-02,  ..., 2.3440e-01, 0.0000e+00,
         1.0000e+00],
        ...,
        [9.4046e-01, 9.6609e-01, 9.5025e-01,  ..., 6.5477e-01, 1.0000e+00,
         1.0000e+00],
        [9.7213e-01, 9.8997e-01, 9.8345e-01,  ..., 6.8902e-01, 1.0000e+00,
         1.0000e+00],
        [1.0000e+00, 1.0000e+00, 9.6296e-01,  ..., 6.9580e-01, 1.0000e+00,
         1.0000e+00]])

In [54]:
yo = y_train.flatten()
yo.shape

torch.Size([15184])

In [23]:
class LSTM(nn.Module):
    
    def __init__(self,input_dim,hidden_dim,seq_len,num_layers=2):
        super(LSTM,self).__init__()
        
        self.hidden_dim = hidden_dim
        self.seq_len = seq_len
        self.num_layers = num_layers
        
        # build out LSTM layer and signmoid (output) layer
        self.lstm = nn.LSTM(
            input_size = input_dim,
            hidden_size = hidden_dim,
            num_layers = num_layers,
            dropout=.5
        )
        
        #sigmoid layer
        # self.linear = nn.Linear(in_features=hidden_dim,out_features=2) 
        self.sigmoid = nn.Sigmoid()
        
    def reset_hidden_state(self):
        self.hidden = (
            torch.zeros(self.num_layers,self.seq_len,self.hidden_dim),
            torch.zeros(self.num_layers,self.seq_len,self.hidden_dim)
        )
        
    def forward(self,input):
        lstm_out, _ = self.lstm(
            input.view(len(input),self.seq_len,-1),
            self.hidden
        )
        y_pred = self.sigmoid(
            lstm_out.view(self.seq_len,len(input),self.hidden_dim)[-1] # pull from last timestep
        )
    
        return y_pred

In [57]:
def train_model(model,train_data,train_labels,test_data=None,test_labels=None):
    loss_fn = nn.CrossEntropyLoss()
    
    optimizer = torch.optim.Adam(model.parameters(),lr=0.01)
    
    num_epochs = 60
    train_hist = np.zeros(num_epochs)
    test_hist = np.zeros(num_epochs)
    
    # reset state of inputs
    for i in range(num_epochs):
        model.reset_hidden_state()
        
        y_pred = model(X_train)
        loss = loss_fn(y_pred,y_train.flatten())
        
        if test_data is not None:
            with torch.no_grad():
                y_test_pred = model(X_test)
                test_loss = loss_fn(y_test_pred,y_test)
            test_hist[i] = test_loss.item()
            
            # print results every 10 epochs
            if i % 10 == 0:
                print('Epoch number:{} train loss: {} test loss: {}'.format(i,loss.item(),test_loss.item()))
        elif i % 10 == 0:
            print('Epoch number:{} train loss: {}'.format(i,loss.item()))
            
        train_hist[i] = loss.item()
        
        optimizer.zero_grad()
        
        loss.backward()
        
        optimizer.step()

    return model.eval(), train_hist, test_hist

In [58]:
model = LSTM(16,512,seq_len=seq_length,num_layers=2)

In [59]:
model,train_hist,test_hist = train_model(model,X_train,y_train,X_test,y_test)

ValueError: Expected input batch_size (949) to match target batch_size (15184).

In [ ]:
X_train[:1]

In [ ]:
y_train[:1]

In [36]:
949*16

15184